### ISSUE TITLE
Index Json File to Fedora 4

### ISSUE THREAD

**Issue by andybuki** [fcrepo4-exts/fcrepo-camel#143]
I try to index data in fedora 4 from json file, using following code:

                     `from("file:data2")
                    .unmarshal(gsonDataFormat)
                    .setBody().simple("${body.products}")
                    .split().body()                                     
                    .to("fcrepo:10.46.3.100:8080/fcrepo-webapp-4.7.4/rest");`
Simular code works if i try to index to Solr, but with Fedora 4.
Do you know should i add something else?

**Comment by andybuki** [comment]
It works now! I added following code:

> .setHeader(Exchange.HTTP_METHOD, constant("POST"))                  
 .setHeader(Exchange.CONTENT_TYPE, constant("application/json"))

It creates in Fedora an objects but without any fields from json file.
Example:

> fedora: created
2017-09-29T09:51:25.52Z
fedora: createdBy
bypassAdmin
fedora: hasParent
http://10.46.3.100:8080/fcrepo-webapp-4.7.4/rest/
fedora: lastModified
2017-09-29T09:51:25.52Z
fedora: lastModifiedBy
bypassAdmin
fedora: writable
true

I transfer the json structure in body,

> .unmarshal(gsonDataFormat)
                        .setBody().simple("${body.products}")

using 

> final GsonDataFormat gsonDataFormat = new GsonDataFormat();
        gsonDataFormat.setUnmarshalType(Products.class);

It indexes well into Solr with whole json file data and structure.
Do you know how to get in Fedora simular structure:


Best regards
Andrey

**Comment by bseeger** [comment]
Hello Audrey, 
Are you trying to have fedora read that JSON file as RDF data or have it treat the JSON as a binary and store it that way?   I suspect that you'd like it parse that file as RDF. 

If you want the JSON to be interpreted as RDF, then it needs to be in JSON-LD format and the mimetype should be "application/ld+json" -- fedora4 does not know how to read JSON as RDF, but it does understand JSON-LD (https://json-ld.org/). 

When  you present a mime type that isn't a RDF mimetype (like JSON), fedora will create a NonRdfResource (aka, binary) of that data. 

Best,
Bethany

**Comment by andybuki** [comment]
Thanks a lot. 
I got it working.
